services:
  - type: web
    name: foco-19-app
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false # Preencha no painel do Render
      - key: APP_URL
        generateValue: true # O Render preenche com a URL do app
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false # Preencha com o host do Supabase
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false # Preencha com o usuário do Supabase
      - key: DB_PASSWORD
        sync: false # Preencha com a senha do Supabase
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: SEED_DATABASE
        value: false
